# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ad157f4a-b51d-4760-a774-4ac86322f9c2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ad157f4a-b51d-4760-a774-4ac86322f9c2".device = "/dev/disk/by-uuid/ad157f4a-b51d-4760-a774-4ac86322f9c2";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F6C2-E304";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
